### PR TITLE
treewide: add A20e support

### PR DESCRIPTION
**Pull request by Royna2544**
It would be great if our phone, Galaxy A20e which uses same chipset as A10, can get kernel patches too.

### CODE REVIEW

**Comment by Royna2544** [comment]
Current Status:
Kernel for A20e built with your repo's patches fully working
Now trying to find out a way to properly overclock

**Comment by Royna2544** [comment]
I found out that if you disable CONFIG_ARM_EXYNOSS_UFC, CPU 
Screenshot:
Screenshot_20210414-171325_Device Info HW+
overclocking works to 2.1Ghz

**Comment by Chatur27** [comment]
Do you have telegram so that we can better discuss ?

**Comment by Royna2544** [comment]
Yes I have one

**Comment by Chatur27** [comment]
> Yes I have one

Contact me @chatur2709 on telegram
I will wait for you

**Comment by Royna2544** [comment]
OK. I have sent you a message

**Pull request closed without merging**
